#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Biblioteca")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertANGAJATI(ANGAJATI instance);
    partial void UpdateANGAJATI(ANGAJATI instance);
    partial void DeleteANGAJATI(ANGAJATI instance);
    partial void InsertCARTI(CARTI instance);
    partial void UpdateCARTI(CARTI instance);
    partial void DeleteCARTI(CARTI instance);
    partial void InsertNOMSPORURI(NOMSPORURI instance);
    partial void UpdateNOMSPORURI(NOMSPORURI instance);
    partial void DeleteNOMSPORURI(NOMSPORURI instance);
    partial void InsertPONTAJ(PONTAJ instance);
    partial void UpdatePONTAJ(PONTAJ instance);
    partial void DeletePONTAJ(PONTAJ instance);
    partial void InsertSALARIZARE(SALARIZARE instance);
    partial void UpdateSALARIZARE(SALARIZARE instance);
    partial void DeleteSALARIZARE(SALARIZARE instance);
    partial void InsertVALSPORURI(VALSPORURI instance);
    partial void UpdateVALSPORURI(VALSPORURI instance);
    partial void DeleteVALSPORURI(VALSPORURI instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Biblioteca.Properties.Settings.Default.BibliotecaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ABONATI> ABONATIs
		{
			get
			{
				return this.GetTable<ABONATI>();
			}
		}
		
		public System.Data.Linq.Table<ANGAJATI> ANGAJATIs
		{
			get
			{
				return this.GetTable<ANGAJATI>();
			}
		}
		
		public System.Data.Linq.Table<CARTI> CARTIs
		{
			get
			{
				return this.GetTable<CARTI>();
			}
		}
		
		public System.Data.Linq.Table<NOMSPORURI> NOMSPORURIs
		{
			get
			{
				return this.GetTable<NOMSPORURI>();
			}
		}
		
		public System.Data.Linq.Table<PONTAJ> PONTAJs
		{
			get
			{
				return this.GetTable<PONTAJ>();
			}
		}
		
		public System.Data.Linq.Table<SALARIZARE> SALARIZAREs
		{
			get
			{
				return this.GetTable<SALARIZARE>();
			}
		}
		
		public System.Data.Linq.Table<VALSPORURI> VALSPORURIs
		{
			get
			{
				return this.GetTable<VALSPORURI>();
			}
		}
		
		public System.Data.Linq.Table<usr> usrs
		{
			get
			{
				return this.GetTable<usr>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ABONATI")]
	public partial class ABONATI
	{
		
		private System.Nullable<long> _ID;
		
		private System.Nullable<long> _ID_CARTI;
		
		private string _NUME;
		
		private string _PRENUME;
		
		private System.Nullable<decimal> _CNP;
		
		private string _ADRESA;
		
		private string _SERIE_CI;
		
		private System.Nullable<decimal> _NR_CI;
		
		private System.Nullable<System.DateTime> _DATA_IMPRUMUT;
		
		private System.Nullable<System.DateTime> _DATA_RETURNARE;
		
		private System.Nullable<System.DateTime> _TERMEN_RESTITUIRE;
		
		private System.Nullable<decimal> _NUMAR_RETURNATE;
		
		private string _MOTIV;
		
		private System.Nullable<decimal> _COTA_PENALIZARE;
		
		private System.Nullable<decimal> _VALOARE_DE_RESTITUIT;
		
		public ABONATI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt")]
		public System.Nullable<long> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CARTI", DbType="BigInt")]
		public System.Nullable<long> ID_CARTI
		{
			get
			{
				return this._ID_CARTI;
			}
			set
			{
				if ((this._ID_CARTI != value))
				{
					this._ID_CARTI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUME", DbType="VarChar(100)")]
		public string NUME
		{
			get
			{
				return this._NUME;
			}
			set
			{
				if ((this._NUME != value))
				{
					this._NUME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRENUME", DbType="VarChar(100)")]
		public string PRENUME
		{
			get
			{
				return this._PRENUME;
			}
			set
			{
				if ((this._PRENUME != value))
				{
					this._PRENUME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNP", DbType="Decimal(13,0)")]
		public System.Nullable<decimal> CNP
		{
			get
			{
				return this._CNP;
			}
			set
			{
				if ((this._CNP != value))
				{
					this._CNP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRESA", DbType="VarChar(200)")]
		public string ADRESA
		{
			get
			{
				return this._ADRESA;
			}
			set
			{
				if ((this._ADRESA != value))
				{
					this._ADRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIE_CI", DbType="VarChar(2)")]
		public string SERIE_CI
		{
			get
			{
				return this._SERIE_CI;
			}
			set
			{
				if ((this._SERIE_CI != value))
				{
					this._SERIE_CI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_CI", DbType="Decimal(6,0)")]
		public System.Nullable<decimal> NR_CI
		{
			get
			{
				return this._NR_CI;
			}
			set
			{
				if ((this._NR_CI != value))
				{
					this._NR_CI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_IMPRUMUT", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DATA_IMPRUMUT
		{
			get
			{
				return this._DATA_IMPRUMUT;
			}
			set
			{
				if ((this._DATA_IMPRUMUT != value))
				{
					this._DATA_IMPRUMUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_RETURNARE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DATA_RETURNARE
		{
			get
			{
				return this._DATA_RETURNARE;
			}
			set
			{
				if ((this._DATA_RETURNARE != value))
				{
					this._DATA_RETURNARE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMEN_RESTITUIRE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TERMEN_RESTITUIRE
		{
			get
			{
				return this._TERMEN_RESTITUIRE;
			}
			set
			{
				if ((this._TERMEN_RESTITUIRE != value))
				{
					this._TERMEN_RESTITUIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMAR_RETURNATE", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> NUMAR_RETURNATE
		{
			get
			{
				return this._NUMAR_RETURNATE;
			}
			set
			{
				if ((this._NUMAR_RETURNATE != value))
				{
					this._NUMAR_RETURNATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTIV", DbType="VarChar(250)")]
		public string MOTIV
		{
			get
			{
				return this._MOTIV;
			}
			set
			{
				if ((this._MOTIV != value))
				{
					this._MOTIV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COTA_PENALIZARE", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> COTA_PENALIZARE
		{
			get
			{
				return this._COTA_PENALIZARE;
			}
			set
			{
				if ((this._COTA_PENALIZARE != value))
				{
					this._COTA_PENALIZARE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOARE_DE_RESTITUIT", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> VALOARE_DE_RESTITUIT
		{
			get
			{
				return this._VALOARE_DE_RESTITUIT;
			}
			set
			{
				if ((this._VALOARE_DE_RESTITUIT != value))
				{
					this._VALOARE_DE_RESTITUIT = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ANGAJATI")]
	public partial class ANGAJATI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<decimal> _MARCA;
		
		private string _NUME;
		
		private string _PRENUME;
		
		private System.Nullable<decimal> _CNP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnMARCAChanging(System.Nullable<decimal> value);
    partial void OnMARCAChanged();
    partial void OnNUMEChanging(string value);
    partial void OnNUMEChanged();
    partial void OnPRENUMEChanging(string value);
    partial void OnPRENUMEChanged();
    partial void OnCNPChanging(System.Nullable<decimal> value);
    partial void OnCNPChanged();
    #endregion
		
		public ANGAJATI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARCA", DbType="Decimal(6,0)")]
		public System.Nullable<decimal> MARCA
		{
			get
			{
				return this._MARCA;
			}
			set
			{
				if ((this._MARCA != value))
				{
					this.OnMARCAChanging(value);
					this.SendPropertyChanging();
					this._MARCA = value;
					this.SendPropertyChanged("MARCA");
					this.OnMARCAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUME", DbType="NVarChar(100)")]
		public string NUME
		{
			get
			{
				return this._NUME;
			}
			set
			{
				if ((this._NUME != value))
				{
					this.OnNUMEChanging(value);
					this.SendPropertyChanging();
					this._NUME = value;
					this.SendPropertyChanged("NUME");
					this.OnNUMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRENUME", DbType="NVarChar(150)")]
		public string PRENUME
		{
			get
			{
				return this._PRENUME;
			}
			set
			{
				if ((this._PRENUME != value))
				{
					this.OnPRENUMEChanging(value);
					this.SendPropertyChanging();
					this._PRENUME = value;
					this.SendPropertyChanged("PRENUME");
					this.OnPRENUMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNP", DbType="Decimal(13,0)")]
		public System.Nullable<decimal> CNP
		{
			get
			{
				return this._CNP;
			}
			set
			{
				if ((this._CNP != value))
				{
					this.OnCNPChanging(value);
					this.SendPropertyChanging();
					this._CNP = value;
					this.SendPropertyChanged("CNP");
					this.OnCNPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CARTI")]
	public partial class CARTI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _TTLU;
		
		private string _AUTOR;
		
		private System.Nullable<System.DateTime> _DATA_PUBLICARE;
		
		private System.Nullable<decimal> _NR_EXEMPLARE;
		
		private System.Nullable<decimal> _PRET;
		
		private System.Nullable<decimal> _STARE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnTTLUChanging(string value);
    partial void OnTTLUChanged();
    partial void OnAUTORChanging(string value);
    partial void OnAUTORChanged();
    partial void OnDATA_PUBLICAREChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_PUBLICAREChanged();
    partial void OnNR_EXEMPLAREChanging(System.Nullable<decimal> value);
    partial void OnNR_EXEMPLAREChanged();
    partial void OnPRETChanging(System.Nullable<decimal> value);
    partial void OnPRETChanged();
    partial void OnSTAREChanging(System.Nullable<decimal> value);
    partial void OnSTAREChanged();
    #endregion
		
		public CARTI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTLU", DbType="VarChar(100)")]
		public string TTLU
		{
			get
			{
				return this._TTLU;
			}
			set
			{
				if ((this._TTLU != value))
				{
					this.OnTTLUChanging(value);
					this.SendPropertyChanging();
					this._TTLU = value;
					this.SendPropertyChanged("TTLU");
					this.OnTTLUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTOR", DbType="VarChar(100)")]
		public string AUTOR
		{
			get
			{
				return this._AUTOR;
			}
			set
			{
				if ((this._AUTOR != value))
				{
					this.OnAUTORChanging(value);
					this.SendPropertyChanging();
					this._AUTOR = value;
					this.SendPropertyChanged("AUTOR");
					this.OnAUTORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_PUBLICARE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DATA_PUBLICARE
		{
			get
			{
				return this._DATA_PUBLICARE;
			}
			set
			{
				if ((this._DATA_PUBLICARE != value))
				{
					this.OnDATA_PUBLICAREChanging(value);
					this.SendPropertyChanging();
					this._DATA_PUBLICARE = value;
					this.SendPropertyChanged("DATA_PUBLICARE");
					this.OnDATA_PUBLICAREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_EXEMPLARE", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> NR_EXEMPLARE
		{
			get
			{
				return this._NR_EXEMPLARE;
			}
			set
			{
				if ((this._NR_EXEMPLARE != value))
				{
					this.OnNR_EXEMPLAREChanging(value);
					this.SendPropertyChanging();
					this._NR_EXEMPLARE = value;
					this.SendPropertyChanged("NR_EXEMPLARE");
					this.OnNR_EXEMPLAREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRET", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> PRET
		{
			get
			{
				return this._PRET;
			}
			set
			{
				if ((this._PRET != value))
				{
					this.OnPRETChanging(value);
					this.SendPropertyChanging();
					this._PRET = value;
					this.SendPropertyChanged("PRET");
					this.OnPRETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARE", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> STARE
		{
			get
			{
				return this._STARE;
			}
			set
			{
				if ((this._STARE != value))
				{
					this.OnSTAREChanging(value);
					this.SendPropertyChanging();
					this._STARE = value;
					this.SendPropertyChanged("STARE");
					this.OnSTAREChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOMSPORURI")]
	public partial class NOMSPORURI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _COD_SPOR;
		
		private string _DENUMIRE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnCOD_SPORChanging(string value);
    partial void OnCOD_SPORChanged();
    partial void OnDENUMIREChanging(string value);
    partial void OnDENUMIREChanged();
    #endregion
		
		public NOMSPORURI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_SPOR", DbType="VarChar(10)")]
		public string COD_SPOR
		{
			get
			{
				return this._COD_SPOR;
			}
			set
			{
				if ((this._COD_SPOR != value))
				{
					this.OnCOD_SPORChanging(value);
					this.SendPropertyChanging();
					this._COD_SPOR = value;
					this.SendPropertyChanged("COD_SPOR");
					this.OnCOD_SPORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENUMIRE", DbType="VarChar(50)")]
		public string DENUMIRE
		{
			get
			{
				return this._DENUMIRE;
			}
			set
			{
				if ((this._DENUMIRE != value))
				{
					this.OnDENUMIREChanging(value);
					this.SendPropertyChanging();
					this._DENUMIRE = value;
					this.SendPropertyChanged("DENUMIRE");
					this.OnDENUMIREChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PONTAJ")]
	public partial class PONTAJ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _ID_SALARIZARE;
		
		private System.Nullable<decimal> _ZL_IN_LUNA;
		
		private System.Nullable<decimal> _ZEF_LUCRATE;
		
		private System.Nullable<decimal> _ZILE_CO;
		
		private System.Nullable<decimal> _ZILE_INV;
		
		private System.Nullable<decimal> _ZILE_NEM;
		
		private System.Nullable<decimal> _ZILE_MED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnID_SALARIZAREChanging(System.Nullable<long> value);
    partial void OnID_SALARIZAREChanged();
    partial void OnZL_IN_LUNAChanging(System.Nullable<decimal> value);
    partial void OnZL_IN_LUNAChanged();
    partial void OnZEF_LUCRATEChanging(System.Nullable<decimal> value);
    partial void OnZEF_LUCRATEChanged();
    partial void OnZILE_COChanging(System.Nullable<decimal> value);
    partial void OnZILE_COChanged();
    partial void OnZILE_INVChanging(System.Nullable<decimal> value);
    partial void OnZILE_INVChanged();
    partial void OnZILE_NEMChanging(System.Nullable<decimal> value);
    partial void OnZILE_NEMChanged();
    partial void OnZILE_MEDChanging(System.Nullable<decimal> value);
    partial void OnZILE_MEDChanged();
    #endregion
		
		public PONTAJ()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SALARIZARE", DbType="BigInt")]
		public System.Nullable<long> ID_SALARIZARE
		{
			get
			{
				return this._ID_SALARIZARE;
			}
			set
			{
				if ((this._ID_SALARIZARE != value))
				{
					this.OnID_SALARIZAREChanging(value);
					this.SendPropertyChanging();
					this._ID_SALARIZARE = value;
					this.SendPropertyChanged("ID_SALARIZARE");
					this.OnID_SALARIZAREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZL_IN_LUNA", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> ZL_IN_LUNA
		{
			get
			{
				return this._ZL_IN_LUNA;
			}
			set
			{
				if ((this._ZL_IN_LUNA != value))
				{
					this.OnZL_IN_LUNAChanging(value);
					this.SendPropertyChanging();
					this._ZL_IN_LUNA = value;
					this.SendPropertyChanged("ZL_IN_LUNA");
					this.OnZL_IN_LUNAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZEF_LUCRATE", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> ZEF_LUCRATE
		{
			get
			{
				return this._ZEF_LUCRATE;
			}
			set
			{
				if ((this._ZEF_LUCRATE != value))
				{
					this.OnZEF_LUCRATEChanging(value);
					this.SendPropertyChanging();
					this._ZEF_LUCRATE = value;
					this.SendPropertyChanged("ZEF_LUCRATE");
					this.OnZEF_LUCRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZILE_CO", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> ZILE_CO
		{
			get
			{
				return this._ZILE_CO;
			}
			set
			{
				if ((this._ZILE_CO != value))
				{
					this.OnZILE_COChanging(value);
					this.SendPropertyChanging();
					this._ZILE_CO = value;
					this.SendPropertyChanged("ZILE_CO");
					this.OnZILE_COChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZILE_INV", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> ZILE_INV
		{
			get
			{
				return this._ZILE_INV;
			}
			set
			{
				if ((this._ZILE_INV != value))
				{
					this.OnZILE_INVChanging(value);
					this.SendPropertyChanging();
					this._ZILE_INV = value;
					this.SendPropertyChanged("ZILE_INV");
					this.OnZILE_INVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZILE_NEM", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> ZILE_NEM
		{
			get
			{
				return this._ZILE_NEM;
			}
			set
			{
				if ((this._ZILE_NEM != value))
				{
					this.OnZILE_NEMChanging(value);
					this.SendPropertyChanging();
					this._ZILE_NEM = value;
					this.SendPropertyChanged("ZILE_NEM");
					this.OnZILE_NEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZILE_MED", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> ZILE_MED
		{
			get
			{
				return this._ZILE_MED;
			}
			set
			{
				if ((this._ZILE_MED != value))
				{
					this.OnZILE_MEDChanging(value);
					this.SendPropertyChanging();
					this._ZILE_MED = value;
					this.SendPropertyChanged("ZILE_MED");
					this.OnZILE_MEDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SALARIZARE")]
	public partial class SALARIZARE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _ID_ANGAJAT;
		
		private string _FUNCTIA;
		
		private string _LOCMUNCA;
		
		private System.Nullable<decimal> _SALBAZA;
		
		private System.Nullable<decimal> _SALEFECTIV;
		
		private System.Nullable<decimal> _SALBRUT;
		
		private System.Nullable<decimal> _VENITNET_;
		
		private System.Nullable<decimal> _SALARIUNET_;
		
		private System.Nullable<decimal> _RESTPLATA;
		
		private System.Nullable<decimal> _RESTCARD;
		
		private System.Nullable<decimal> _LUNA;
		
		private System.Nullable<decimal> _ANUL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnID_ANGAJATChanging(System.Nullable<long> value);
    partial void OnID_ANGAJATChanged();
    partial void OnFUNCTIAChanging(string value);
    partial void OnFUNCTIAChanged();
    partial void OnLOCMUNCAChanging(string value);
    partial void OnLOCMUNCAChanged();
    partial void OnSALBAZAChanging(System.Nullable<decimal> value);
    partial void OnSALBAZAChanged();
    partial void OnSALEFECTIVChanging(System.Nullable<decimal> value);
    partial void OnSALEFECTIVChanged();
    partial void OnSALBRUTChanging(System.Nullable<decimal> value);
    partial void OnSALBRUTChanged();
    partial void OnVENITNET_Changing(System.Nullable<decimal> value);
    partial void OnVENITNET_Changed();
    partial void OnSALARIUNET_Changing(System.Nullable<decimal> value);
    partial void OnSALARIUNET_Changed();
    partial void OnRESTPLATAChanging(System.Nullable<decimal> value);
    partial void OnRESTPLATAChanged();
    partial void OnRESTCARDChanging(System.Nullable<decimal> value);
    partial void OnRESTCARDChanged();
    partial void OnLUNAChanging(System.Nullable<decimal> value);
    partial void OnLUNAChanged();
    partial void OnANULChanging(System.Nullable<decimal> value);
    partial void OnANULChanged();
    #endregion
		
		public SALARIZARE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ANGAJAT", DbType="BigInt")]
		public System.Nullable<long> ID_ANGAJAT
		{
			get
			{
				return this._ID_ANGAJAT;
			}
			set
			{
				if ((this._ID_ANGAJAT != value))
				{
					this.OnID_ANGAJATChanging(value);
					this.SendPropertyChanging();
					this._ID_ANGAJAT = value;
					this.SendPropertyChanged("ID_ANGAJAT");
					this.OnID_ANGAJATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUNCTIA", DbType="VarChar(100)")]
		public string FUNCTIA
		{
			get
			{
				return this._FUNCTIA;
			}
			set
			{
				if ((this._FUNCTIA != value))
				{
					this.OnFUNCTIAChanging(value);
					this.SendPropertyChanging();
					this._FUNCTIA = value;
					this.SendPropertyChanged("FUNCTIA");
					this.OnFUNCTIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCMUNCA", DbType="VarChar(150)")]
		public string LOCMUNCA
		{
			get
			{
				return this._LOCMUNCA;
			}
			set
			{
				if ((this._LOCMUNCA != value))
				{
					this.OnLOCMUNCAChanging(value);
					this.SendPropertyChanging();
					this._LOCMUNCA = value;
					this.SendPropertyChanged("LOCMUNCA");
					this.OnLOCMUNCAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALBAZA", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SALBAZA
		{
			get
			{
				return this._SALBAZA;
			}
			set
			{
				if ((this._SALBAZA != value))
				{
					this.OnSALBAZAChanging(value);
					this.SendPropertyChanging();
					this._SALBAZA = value;
					this.SendPropertyChanged("SALBAZA");
					this.OnSALBAZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALEFECTIV", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SALEFECTIV
		{
			get
			{
				return this._SALEFECTIV;
			}
			set
			{
				if ((this._SALEFECTIV != value))
				{
					this.OnSALEFECTIVChanging(value);
					this.SendPropertyChanging();
					this._SALEFECTIV = value;
					this.SendPropertyChanged("SALEFECTIV");
					this.OnSALEFECTIVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALBRUT", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SALBRUT
		{
			get
			{
				return this._SALBRUT;
			}
			set
			{
				if ((this._SALBRUT != value))
				{
					this.OnSALBRUTChanging(value);
					this.SendPropertyChanging();
					this._SALBRUT = value;
					this.SendPropertyChanged("SALBRUT");
					this.OnSALBRUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[VENITNET ]", Storage="_VENITNET_", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> VENITNET_
		{
			get
			{
				return this._VENITNET_;
			}
			set
			{
				if ((this._VENITNET_ != value))
				{
					this.OnVENITNET_Changing(value);
					this.SendPropertyChanging();
					this._VENITNET_ = value;
					this.SendPropertyChanged("VENITNET_");
					this.OnVENITNET_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SALARIUNET ]", Storage="_SALARIUNET_", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SALARIUNET_
		{
			get
			{
				return this._SALARIUNET_;
			}
			set
			{
				if ((this._SALARIUNET_ != value))
				{
					this.OnSALARIUNET_Changing(value);
					this.SendPropertyChanging();
					this._SALARIUNET_ = value;
					this.SendPropertyChanged("SALARIUNET_");
					this.OnSALARIUNET_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESTPLATA", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> RESTPLATA
		{
			get
			{
				return this._RESTPLATA;
			}
			set
			{
				if ((this._RESTPLATA != value))
				{
					this.OnRESTPLATAChanging(value);
					this.SendPropertyChanging();
					this._RESTPLATA = value;
					this.SendPropertyChanged("RESTPLATA");
					this.OnRESTPLATAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESTCARD", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> RESTCARD
		{
			get
			{
				return this._RESTCARD;
			}
			set
			{
				if ((this._RESTCARD != value))
				{
					this.OnRESTCARDChanging(value);
					this.SendPropertyChanging();
					this._RESTCARD = value;
					this.SendPropertyChanged("RESTCARD");
					this.OnRESTCARDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUNA", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> LUNA
		{
			get
			{
				return this._LUNA;
			}
			set
			{
				if ((this._LUNA != value))
				{
					this.OnLUNAChanging(value);
					this.SendPropertyChanging();
					this._LUNA = value;
					this.SendPropertyChanged("LUNA");
					this.OnLUNAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANUL", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> ANUL
		{
			get
			{
				return this._ANUL;
			}
			set
			{
				if ((this._ANUL != value))
				{
					this.OnANULChanging(value);
					this.SendPropertyChanging();
					this._ANUL = value;
					this.SendPropertyChanged("ANUL");
					this.OnANULChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VALSPORURI")]
	public partial class VALSPORURI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _ID_SPOR;
		
		private System.Nullable<decimal> _VALOARE_CALCULATA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnID_SPORChanging(System.Nullable<long> value);
    partial void OnID_SPORChanged();
    partial void OnVALOARE_CALCULATAChanging(System.Nullable<decimal> value);
    partial void OnVALOARE_CALCULATAChanged();
    #endregion
		
		public VALSPORURI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SPOR", DbType="BigInt")]
		public System.Nullable<long> ID_SPOR
		{
			get
			{
				return this._ID_SPOR;
			}
			set
			{
				if ((this._ID_SPOR != value))
				{
					this.OnID_SPORChanging(value);
					this.SendPropertyChanging();
					this._ID_SPOR = value;
					this.SendPropertyChanged("ID_SPOR");
					this.OnID_SPORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOARE_CALCULATA", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> VALOARE_CALCULATA
		{
			get
			{
				return this._VALOARE_CALCULATA;
			}
			set
			{
				if ((this._VALOARE_CALCULATA != value))
				{
					this.OnVALOARE_CALCULATAChanging(value);
					this.SendPropertyChanging();
					this._VALOARE_CALCULATA = value;
					this.SendPropertyChanged("VALOARE_CALCULATA");
					this.OnVALOARE_CALCULATAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usr")]
	public partial class usr
	{
		
		private string _nume_utilizator;
		
		private string _parola;
		
		public usr()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nume_utilizator", DbType="VarChar(50)")]
		public string nume_utilizator
		{
			get
			{
				return this._nume_utilizator;
			}
			set
			{
				if ((this._nume_utilizator != value))
				{
					this._nume_utilizator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parola", DbType="VarChar(50)")]
		public string parola
		{
			get
			{
				return this._parola;
			}
			set
			{
				if ((this._parola != value))
				{
					this._parola = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
